// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIUFOoB6Q-DvygXF82xBQN6nrgfjGvLbA',
    appId: '1:368583845938:web:b327222e0d95a0042d342b',
    messagingSenderId: '368583845938',
    projectId: 'music-16f5c',
    authDomain: 'music-16f5c.firebaseapp.com',
    databaseURL: 'https://music-16f5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-16f5c.firebasestorage.app',
    measurementId: 'G-E91HVJJP7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW6xdddiTToA4rY83TMYlxfuGFnE6It7M',
    appId: '1:368583845938:android:4ce90ebd323141f32d342b',
    messagingSenderId: '368583845938',
    projectId: 'music-16f5c',
    databaseURL: 'https://music-16f5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-16f5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbmaSkA0gpXOz5QyFD2Ca0DmWN6qo2G4o',
    appId: '1:368583845938:ios:d9b31e964e6de3592d342b',
    messagingSenderId: '368583845938',
    projectId: 'music-16f5c',
    databaseURL: 'https://music-16f5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-16f5c.firebasestorage.app',
    androidClientId: '368583845938-0h1vsnbg5f8gb2ohvmfqe6v4qidbjeva.apps.googleusercontent.com',
    iosClientId: '368583845938-olhvkoaqj20q6nsp642dh61i33crmovq.apps.googleusercontent.com',
    iosBundleId: 'com.musichub.musicHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbmaSkA0gpXOz5QyFD2Ca0DmWN6qo2G4o',
    appId: '1:368583845938:ios:d9b31e964e6de3592d342b',
    messagingSenderId: '368583845938',
    projectId: 'music-16f5c',
    databaseURL: 'https://music-16f5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-16f5c.firebasestorage.app',
    androidClientId: '368583845938-0h1vsnbg5f8gb2ohvmfqe6v4qidbjeva.apps.googleusercontent.com',
    iosClientId: '368583845938-olhvkoaqj20q6nsp642dh61i33crmovq.apps.googleusercontent.com',
    iosBundleId: 'com.musichub.musicHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIUFOoB6Q-DvygXF82xBQN6nrgfjGvLbA',
    appId: '1:368583845938:web:b327222e0d95a0042d342b',
    messagingSenderId: '368583845938',
    projectId: 'music-16f5c',
    authDomain: 'music-16f5c.firebaseapp.com',
    databaseURL: 'https://music-16f5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-16f5c.firebasestorage.app',
    measurementId: 'G-E91HVJJP7D',
  );

}